### ISSUE TITLE
how the exe files in the executables folder are made？

### ISSUE THREAD

**Issue by wangez** [TangoChen/KinectV2MouseControl#2]
I need to display the picture taken by Kinect while controlling the mouse。So I have to change the code。But I don't know how to package the code into .exe after change it;

**Comment by TangoChen** [comment]
Hi wangez. Under the [Build] menu on Visual Studio, either clicking [Build Solution] or [Build KinectV2MouseControl], then you can find the exe files under “bin\Release” or “bin\Debug” of project folder, according to what the project configuration is. If it’s in Release mode, you’ll get a release one, which you may most probably want to have for using, instead of a Debug one.
